### ISSUE TITLE
Cortix module has no attribute 'ports'

### ISSUE THREAD

**Issue by seamuss1** [dpploy/cortix#178]
I'm Having trouble developing a Cortix module for dados. How should the ports be incorporated into the code?
Is it possible to have the option to omit port names and assigning ports?
```
Traceback (most recent call last):
File "dados.py", line 27, in <module>
app.run()
File "dados.py", line 19, in run
self.rs232.add_port(p1)                                                                                                                                               File "/home/pi/cortix/cortix/src/module.py", line 55, in add_port
if port not in self.ports:
AttributeError: 'RS_232' object has no attribute 'ports'

```

**Comment by seamuss1** [comment]
I found the error. I forgot to add the `super().__init__()` statement. So the Module inheritance did not import correctly.
